### ISSUE TITLE
Cant get it working on Windows10 Home 64

### ISSUE THREAD

**Issue by El-Mare** [hanselb/HyperionScreenCap#1]
Hello @djhansel 
VERY nice work, thanks for that!
Unfortunately I cant get it working on my Win10 Home 64 HTPC. I installed the full package of DirectX9 and edited the config to my setup. After starting the exe, the grey icon appears in tray and just disappears a few seconds later.
The same procedure instantly worked on a Win7 Prof 64 machine like a charm.
Do you have any recommendations regarding Win10?

**Comment by hanselb** [comment]
Hey @El-Mare. I experienced the same issue when the SlimDX.dll was not copied in the installation. I have to do some testing on windows 10 Home edition to see why this is happening.

**Comment by El-Mare** [comment]
Hi @djhansel Thanks for digging into this. Will retest this with another Win 10 Home 64 machine later...
What do you mean by 

> when the SlimDX.dll was not copied in the installation

Is there a workaround by copying the SlimDX.dll somewhere manually? Where?

**Comment by hanselb** [comment]
@El-Mare There should be 3 files in the same folder for HyperionScreenCap to work. They are included in the relase zip file.

HyperionScreenCap.exe
HyperionScreenCap.exe.config
SlimDX.dll

**Comment by hanselb** [comment]
Quick update @El-Mare I was able to get it to work on a Windows 10 VM after installing Visual Studio 2015. I am not sure why that seems to be a requirement. I will continue to test and update the installation package once I find what is getting installed by VS that is needed.

**Comment by El-Mare** [comment]
@djhansel thanks for your update. I just found the time to test on a second win 10 Home 64 machine - and it works! The difference to my HTPC is, that on the 2nd PC MS Office is installed - together with MS Visual Studio 2010 Tools for Office Runtime. Also there are several MS Visual C++ Redistributables (2008 - 2013) installed - don't know if they could be involved...
If I can be of any help in finding out, what really is needed for Hyperion Screen Cap to properly work, please let me know!

**Comment by hanselb** [comment]
Hi @El-Mare the solution was installing the Visual C++ 2010 version. I have created an installer that should setup the dependencies. You can download it from [here](https://github.com/djhansel/HyperionScreenCap/releases/download/v1.1/SetupHyperionScreenCap.exe) to test it on your HTPC 
Thanks for the help figuring this out. :smile:
