### ISSUE TITLE
Failed to take screenshot. object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by pete111** [hanselb/HyperionScreenCap#15]
Hello, 
once I start HyperionScreenCap I am getting error in bublebox "Failed to take screenshot. Object reference not set to an instance of an object."

My pc: WinXp, DirectX 9.0

**Comment by wkl001** [comment]
![image](https://user-images.githubusercontent.com/18112469/27768042-b22d9778-5f09-11e7-9bc4-5e1b04bc394f.png)

Got that same problem on Windows 7.
I'm running hyperion on a pi2, ip: 192.168.2.9
![image](https://user-images.githubusercontent.com/18112469/27768050-ea7a3f8c-5f09-11e7-864a-3ce290b0fb42.png)

Am I doing something wrong?


edit: I'm running DX11 64 bits

**Comment by RickDB** [comment]
Added fixes for these kind of issues as they are most likely related to multi monitor or use of display scaling.

@hanselb cleaning up code first but will make a PR soon :)
