### ISSUE TITLE
Create Installer

### ISSUE THREAD

**Issue by hanselb** [hanselb/HyperionScreenCap#2]
Create simple installer package which will setup the correct DirectX version if needed.

**Comment by IDmedia** [comment]
Just a suggestion.. instead of creating a installer you could also include all necessary files using this Nuget: https://github.com/Fody/Costura

Regarding DirectX I would just make a check if it's installed and if not notify the user. :)

**Comment by hanselb** [comment]
Hey @IDmedia thanks for the suggestion. I had some issues embedding the SlimDX.dll libraries with the app but I will give Costura a try.

I found an easy way to check and install dependencies with [Inno setup](https://github.com/jrsoftware/issrc) so adding DirectX / .net 4.0 won't be a problem :)

**Comment by hanselb** [comment]
@IDmedia I was able to use Costura :smile: 
I have also created an installer that sets up all the required dependencies. You can find it here
[https://github.com/djhansel/HyperionScreenCap/releases/latest](https://github.com/djhansel/HyperionScreenCap/releases/latest)
